### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by mmunnis** [bpampuch/pdfmake#1099]
I've started to receive the following error with Google Chrome (Version 60.0.3112.90 (Official Build) (64-bit)) and pdfMake (v0.1.32).

`pdfmake.js:24658 Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.arraySet (http://localhost:19175/content/canvas/js/components/pdfmake.js:24658:13)
    at read_buf (http://localhost:19175/content/canvas/js/components/pdfmake.js:23031:10)
    at fill_window (http://localhost:19175/content/canvas/js/components/pdfmake.js:23246:10)
    at Config.deflate_slow [as func] (http://localhost:19175/content/canvas/js/components/pdfmake.js:23565:8)
    at Object.deflate (http://localhost:19175/content/canvas/js/components/pdfmake.js:24483:39)
    at Zlib._write (http://localhost:19175/content/canvas/js/components/pdfmake.js:22722:34)
    at http://localhost:19175/content/canvas/js/components/pdfmake.js:22665:21
    at Item.run (http://localhost:19175/content/canvas/js/components/pdfmake.js:20369:15)
    at drainQueue (http://localhost:19175/content/canvas/js/components/pdfmake.js:20339:43)`

It's erroring on this line (24658):
`dest.set(src.subarray(src_offs, src_offs+len), dest_offs);`

**Comment by liborm85** [comment]
Please attach docDefinition example for reproduce your problem.
