### ISSUE TITLE
"Uncaught RangeError: Source is too large" using amCharts 3.20.6

### ISSUE THREAD

**Issue by rozza2058** [bpampuch/pdfmake#1106]
I am using amCharts in my application, and their export plugin uses pdfmake. On attempting to export any chart as a pdf, I got a console error as above with the following stack trace:

```
Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.arraySet (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:12:14069)
    at c (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:12:728)
    at f (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:12:1879)
    at St.g [as func] (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:12:4011)
    at Object.E [as deflate] (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:12:12009)
    at i._write (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:11:30645)
    at .../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:11:30026
    at i.run (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:11:6793)
    at r (.../amcharts/3.20.6/plugins/export/libs/pdfmake/pdfmake.min.js:11:6427)
```

I have tested this in Chrome 60.0.3112.90 (Official Build), Microsoft Edge (which spits out a slightly different error about invalid offset when creating typed array) and Firefox (which gives `RangeError: invalid array length`). I noticed a similar issue being raised under #998 - I wanted to raise this as a separate issue because while it seemed related, my issue has nothing to do with browserify, and is reproducible in other browsers with slightly different error messages.

**Comment by liborm85** [comment]
Please attach docDefinition example for reproduce your problem.

**Comment by rozza2058** [comment]
Do you think you could help me to identify how to do this/what information you need exactly? I've mostly been able to ignore the intricacies of pdfmake as it's hidden inside amCharts' export plugin.

**Comment by rozza2058** [comment]
Below is the object `data.docDefinition`, extracted from the result of `pdfMake.createPdf` on line 2025 of `.../amcharts/3.20.6/plugins/export/export.js` - hope that helps

```
{
  "multiplier": 2,
  "pageOrigin": true,
  "images": {},
  "pageOrientation": "portrait",
  "pageMargins": 40,
  "pageSize": "A4",
  "pageSizes": {
    "4A0": [
      4767.87,
      6740.79
    ],
    "2A0": [
      3370.39,
      4767.87
    ],
    "A0": [
      2383.94,
      3370.39
    ],
    "A1": [
      1683.78,
      2383.94
    ],
    "A2": [
      1190.55,
      1683.78
    ],
    "A3": [
      841.89,
      1190.55
    ],
    "A4": [
      595.28,
      841.89
    ],
    "A5": [
      419.53,
      595.28
    ],
    "A6": [
      297.64,
      419.53
    ],
    "A7": [
      209.76,
      297.64
    ],
    "A8": [
      147.4,
      209.76
    ],
    "A9": [
      104.88,
      147.4
    ],
    "A10": [
      73.7,
      104.88
    ],
    "B0": [
      2834.65,
      4008.19
    ],
    "B1": [
      2004.09,
      2834.65
    ],
    "B2": [
      1417.32,
      2004.09
    ],
    "B3": [
      1000.63,
      1417.32
    ],
    "B4": [
      708.66,
      1000.63
    ],
    "B5": [
      498.9,
      708.66
    ],
    "B6": [
      354.33,
      498.9
    ],
    "B7": [
      249.45,
      354.33
    ],
    "B8": [
      175.75,
      249.45
    ],
    "B9": [
      124.72,
      175.75
    ],
    "B10": [
      87.87,
      124.72
    ],
    "C0": [
      2599.37,
      3676.54
    ],
    "C1": [
      1836.85,
      2599.37
    ],
    "C2": [
      1298.27,
      1836.85
    ],
    "C3": [
      918.43,
      1298.27
    ],
    "C4": [
      649.13,
      918.43
    ],
    "C5": [
      459.21,
      649.13
    ],
    "C6": [
      323.15,
      459.21
    ],
    "C7": [
      229.61,
      323.15
    ],
    "C8": [
      161.57,
      229.61
    ],
    "C9": [
      113.39,
      161.57
    ],
    "C10": [
      79.37,
      113.39
    ],
    "RA0": [
      2437.8,
      3458.27
    ],
    "RA1": [
      1729.13,
      2437.8
    ],
    "RA2": [
      1218.9,
      1729.13
    ],
    "RA3": [
      864.57,
      1218.9
    ],
    "RA4": [
      609.45,
      864.57
    ],
    "SRA0": [
      2551.18,
      3628.35
    ],
    "SRA1": [
      1814.17,
      2551.18
    ],
    "SRA2": [
      1275.59,
      1814.17
    ],
    "SRA3": [
      907.09,
      1275.59
    ],
    "SRA4": [
      637.8,
      907.09
    ],
    "EXECUTIVE": [
      521.86,
      756
    ],
    "FOLIO": [
      612,
      936
    ],
    "LEGAL": [
      612,
      1008
    ],
    "LETTER": [
      612,
      792
    ],
    "TABLOID": [
      792,
      1224
    ]
  },
  "position": "bottom-right",
  "enabled": true,
  "menu": [
    {
      "class": "export-main",
      "menu": [
        {
          "label": "Download as ...",
          "menu": [
            {
              "label": "PDF",
              "format": "PDF",
              "content": [
                {
                  "image": "reference",
                  "fit": [
                    523.28,
                    769.89
                  ]
                }
              ]
            },
            "JPG",
            "",
            "SVG",
            "PNG"
          ]
        },
        {
          "label": "Save as ...",
          "menu": [
            {
              "label": "CSV"
            },
            {
              "label": "XLSX"
            }
          ]
        },
        "",
        {
          "label": "Print",
          "format": "PRINT"
        }
      ]
    }
  ],
  "fileName": "Timeline-Volume",
  "drawing": {
    "enabled": true,
    "arrow": "end",
    "lineCap": "butt",
    "mode": "pencil",
    "modes": [
      "pencil",
      "line",
      "arrow"
    ],
    "color": "#000000",
    "colors": [
      "#000000",
      "#FFFFFF",
      "#FF0000",
      "#00FF00",
      "#0000FF"
    ],
    "shapes": [
      "11.svg",
      "14.svg",
      "16.svg",
      "17.svg",
      "20.svg",
      "27.svg"
    ],
    "width": 1,
    "fontSize": 11,
    "widths": [
      1,
      5,
      10,
      15
    ],
    "opacity": 1,
    "opacities": [
      1,
      0.8,
      0.6,
      0.4,
      0.2
    ],
    "autoClose": true
  },
  "label": "PDF",
  "format": "PDF",
  "mimeType": "application/pdf",
  "extension": "pdf",
  "capture": true,
  "action": "download",
  "content": [
    {
      "image": "reference",
      "fit": [
        523.28,
        769.89
      ]
    }
  ],
  "elements": {
    "li": {},
    "a": {},
    "img": {},
    "span": {}
  }
}
```

**Comment by liborm85** [comment]
I need to simulate the situation somewhere to try what is causing the error.
Can you create example demo on http://jsfiddle.net (or other site)?

**Comment by mrm** [comment]
This (and https://github.com/bpampuch/pdfmake/issues/998) is most likely caused by using an old version of pdfmake that contains an old Buffer implementation with the following `subarray` issue: https://github.com/feross/buffer/issues/94.

**Comment by rozza2058** [comment]
@mrm ok, so which version of pdfmake uses a newer Buffer implementation? Maybe I can raise an issue over at amcharts to update the version?

**Comment by liborm85** [comment]
Ok, then with latest (0.1.32) pdfmake version work well.
