### ISSUE TITLE
Cannot set property 'fontDescriptors' of undefined

### ISSUE THREAD

**Issue by meta7x** [bpampuch/pdfmake#1411]
Doing the printer setup, I get the following error from the consctructor of the printer, which seems quite weird to me:

```
TypeError: Cannot set property 'fontDescriptors' of undefined
    at PdfPrinter (/user_code/node_modules/pdfmake/src/printer.js:38:23)
    at Promise (/user_code/src/sendInvoice.js:127:21)
    at generatePDF (/user_code/src/sendInvoice.js:125:10)
    ...
```

I'm using the most basic setup:

```javascript
const PdfPrinter = require('pdfmake')
const base64 = require('base64-stream')

/* ... */

function generatePDF() {
  const fonts = {
    Roboto: {
      normal: '../assets/fonts/Roboto-Regular.ttf',
      bold: '../assets/fonts/Roboto-Medium.ttf',
      italics: '../assets/fonts/Roboto-Italic.ttf',
      bolditalics: '../assets/fonts/Roboto-MediumItalic.ttf'
    }
  }

  return new Promise((resolve, reject) => {
    const dd = getDocDefinition()
    const printer = PdfPrinter(fonts)
    const pdfDoc = printer.createPdfKitDocument(dd)
    const stream = pdfDoc.pipe(base64.encode())

    let dataString = ''
    stream.on('data', chunk => {
      dataString += chunk
    })
    stream.on('end', () => {
      resolve(dataString)
    })
  })
}
```

Am I doing something wrong? It is noteworthy that I'm running Node 6.11.5 on Firebase Functions, but I don't see that being related to this particular error.

**Comment by meta7x** [comment]
Wow, I was getting too tired, thanks so much.
