### ISSUE TITLE
PDF make with angular 6.1.4 

### ISSUE THREAD

**Issue by preetitiwari12** [bpampuch/pdfmake#1655]
Currently we are using angular 6.1.4 facing issue with ng build --prod getting below error

Problem is  when we do ng build –prod we get below error
Module build failed: Error: Debug Failure. False expression.
    at getJSDocTags (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13197:22)
    at getFirstJSDocTag (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13205:24)
    at Object.getJSDocTypeTag (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13154:19)
    at checkParenthesizedExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45628:56)
    at checkExpressionWorker (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45676:28)
    at checkExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45609:42)
    at checkBinaryLikeExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45155:29)    
	at checkBinaryExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45147:20)
    at checkExpressionWorker (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45702:28)
    at checkExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45609:42)
    at checkExpressionCached (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45457:38)
    at getTypeOfExpression (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45577:28)
    at checkDeclarationInitializer (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45469:24)
    at getTypeForVariableLikeDeclaration (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:30738:28)
    at getWidenedTypeForVariableLikeDeclaration (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:30961:24)
    at getTypeOfVariableOrParameterOrProperty (C:\Project\\Client\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:31062:28)

Updating the angular devkit
https://github.com/Microsoft/TypeScript/issues/25067
https://github.com/angular/angular-cli/issues/11192

We tried with  "@angular-devkit/build-angular": "~0.6.8", to 0.10.3, but this solution didn’t worked reason the angular-devkit take the angular/core 7.0.3 in package-lock.json

2.	Found one more solution for the same 
https://github.com/kaburkett/ngx-pdfmake-example,
downloaded it and executed npm build –prod it working, difference found is version of pdfmake is different typescript version and angular-cli 

It has different version of typescript 2.7.2, angular cli -^6.0.8 -  in our application we have typescript  2.9.2 and angular cli 6.1.4

Need to know which version of pdfmake support 6.1.4

**Comment by liborm85** [comment]
Solution is only this https://github.com/bpampuch/pdfmake/issues/1618#issuecomment-462753963 , if it doesn't work, I don't know how to solve.

**Comment by preetitiwari12** [comment]
I have tried by changing 0.6.8 to 0.10.3 in package-lock.json update to 7.0.3 this is creating an issue in application

**Comment by liborm85** [comment]
I tried to make various modifications/fixes. 

Please try these 3 versions of pdfmake:
[pdfmake-fix1.zip](https://github.com/bpampuch/pdfmake/files/2921978/pdfmake-fix1.zip)
[pdfmake-fix2.zip](https://github.com/bpampuch/pdfmake/files/2921979/pdfmake-fix2.zip)
[pdfmake-fix3.zip](https://github.com/bpampuch/pdfmake/files/2921980/pdfmake-fix3.zip)

and write individual results. Thanks.

**Comment by liborm85** [comment]
No reaction.

**Comment by preetitiwari12** [comment]
Sorry for the replying so late i am looking into it.

**Comment by gitPushPuppets** [comment]
I have tried the various methods list before the 3 zip files and none of them work. I am having trouble testing the zip files as I am using Amcharts4 which grabs pdfmake as a dependency. Do you have advice on how I can approach the problem?

**Comment by gitPushPuppets** [comment]
Tested all three pdfmake.js files with ng build --prod and they failed for me.
"@angular/cli": "^6.1.5"
"typescript": "~2.8.0"

**Comment by preetitiwari12** [comment]
It got solved by installing the  version 0.1.31.


All the 3 files are giving same error can you please let us know the version of all three files.

**Comment by liborm85** [comment]
When nothing works, then is no way how to solve it in pdfmake, because bug is in angular. Try to contact angular support.

**Comment by gitPushPuppets** [comment]
> It got solved by installing the version 0.1.31.
> 
> All the 3 files are giving same error can you please let us know the version of all three files.

The three files called pdfmake-fix1[2,3] listed above by liborm85.

**Comment by preetitiwari12** [comment]
> > It got solved by installing the version 0.1.31.
> > All the 3 files are giving same error can you please let us know the version of all three files.
> 
> The three files called pdfmake-fix1[2,3] listed above by liborm85.

No by installing the version 0.1.31 npm pdfmake@0.1.31

**Comment by liborm85** [comment]
pdfmake 0.1.31 uses old pdfkit version. pdfmake 0.1.50+ uses pdfkit version 0.9 which use ES6 syntax and with that angular has a problem. Bug is in angular: https://github.com/angular/angular-cli/issues/11192.
