### ISSUE TITLE
gulp buildWithStandardFonts returns webpack error

### ISSUE THREAD

**Issue by railsstudent** [bpampuch/pdfmake#1668]
When trying to build standard fonts to be used on client-side, the gulp command issues the following error trace:

ModuleBuildError: Module build failed (from ./node_modules/transform-loader/index.js):
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at _class.pp$4.raise (/home/connie/Documents/pdfmake/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:2844:13)
    at _class.pp$1.parseStatement (/home/connie/Documents/pdfmake/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:859:16)
    at _class.parseStatement (/home/connie/Documents/pdfmake/node_modules/acorn-dynamic-import/lib/index.js:63:118)
    at _class.pp$1.parseTopLevel (/home/connie/Documents/pdfmake/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:749:23)
    at _class.parse (/home/connie/Documents/pdfmake/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:552:15)
    at Function.parse (/home/connie/Documents/pdfmake/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:575:35)
    at Object.parse (/home/connie/Documents/pdfmake/node_modules/acorn-node/index.js:26:28)
    at /home/connie/Documents/pdfmake/node_modules/brfs/node_modules/static-module/index.js:54:25
    at ConcatStream.<anonymous> (/home/connie/Documents/pdfmake/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/connie/Documents/pdfmake/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/connie/Documents/pdfmake/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/connie/Documents/pdfmake/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.<anonymous> (/home/connie/Documents/pdfmake/node_modules/duplexer2/index.js:29:14)
    at Object.onceWrapper (events.js:313:30)
    at runLoaders (/home/connie/Documents/pdfmake/node_modules/webpack/lib/NormalModule.js:301:20)
    at /home/connie/Documents/pdfmake/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/connie/Documents/pdfmake/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/connie/Documents/pdfmake/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at DuplexWrapper.<anonymous> (/home/connie/Documents/pdfmake/node_modules/transform-loader/index.js:48:4)
    at emitOne (events.js:116:13)
    at DuplexWrapper.emit (events.js:211:7)
    at DestroyableTransform.<anonymous> (/home/connie/Documents/pdfmake/node_modules/duplexer2/index.js:49:12)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at error (/home/connie/Documents/pdfmake/node_modules/brfs/node_modules/static-module/index.js:168:16)
    at /home/connie/Documents/pdfmake/node_modules/brfs/node_modules/static-module/index.js:59:30
    at ConcatStream.<anonymous> (/home/connie/Documents/pdfmake/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/connie/Documents/pdfmake/node_modules/readable-stream/lib/_stream_writable.js:630:14)

Please kindly advise the resolution to the issue. Thanks.

**Comment by blikblum** [comment]
You should look at https://github.com/webpack-contrib/transform-loader/issues/32.

BTW: since static-module does not support  ES modules there's no way to make it work

**Comment by railsstudent** [comment]
@blikblum  Thanks. Let me give it a try.

**Comment by blikblum** [comment]
Just like i said above.

I used a different implementation of vfs to support  standard fonts in pdfkit.


https://github.com/blikblum/pdfkit-webpack-example

**Comment by liborm85** [comment]
Building pdfmake with standard fonts fixed by commit https://github.com/bpampuch/pdfmake/commit/8d2dd71befa0bf54b0dc3894a46151814f6aafc1.

I didn't see that pdfkit library use es6 syntax in package marked as es5, which broke execution brfs. Pdfkit is transformed to right es5 now. And building pdfmake with standard fonts works ok.

**Comment by liborm85** [comment]
Released in 0.1.54.
