### ISSUE TITLE
Hide empty ToC

### ISSUE THREAD

**Issue by quoininc-huudatran** [bpampuch/pdfmake#1772]
I have no tables in my `docDefinition`, but I get the following error:

```
*** ERROR *** createPdfKitDocument(): TypeError: Cannot read property 'length' of undefined
    at DocMeasure.measureTable (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:532:42)
    at <my-project-root>/node_modules/pdfmake/src/docMeasure.js:56:30
    at StyleContextStack.auto (<my-project-root>/node_modules/pdfmake/src/styleContextStack.js:140:15)
    at DocMeasure.measureNode (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:43:25)
    at DocMeasure.measureToc (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:250:25)
    at <my-project-root>/node_modules/pdfmake/src/docMeasure.js:60:30
    at StyleContextStack.auto (<my-project-root>/node_modules/pdfmake/src/styleContextStack.js:140:15)
    at DocMeasure.measureNode (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:43:25)
    at DocMeasure.measureVerticalContainer (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:262:19)
    at <my-project-root>/node_modules/pdfmake/src/docMeasure.js:50:30
    at StyleContextStack.auto (<my-project-root>/node_modules/pdfmake/src/styleContextStack.js:140:15)
    at DocMeasure.measureNode (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:43:25)
    at DocMeasure.measureDocument (<my-project-root>/node_modules/pdfmake/src/docMeasure.js:36:14)
    at LayoutBuilder.tryLayoutDocument (<my-project-root>/node_modules/pdfmake/src/layoutBuilder.js:150:33)
    at LayoutBuilder.layoutDocument (<my-project-root>/node_modules/pdfmake/src/layoutBuilder.js:137:20)
    at PdfPrinter.createPdfKitDocument (<my-project-root>/node_modules/pdfmake/src/printer.js:119:22)
```

I put a `console.log("node.table=", node.table);` just above that `for()` loop, and this is the output:

```
node.table= { dontBreakRows: true,
  widths: [ { width: '*' }, { width: 'auto' } ],
  body: [] }
```

I dumped my docDefinition in a 1.2M json file if needed.

**Comment by liborm85** [comment]
Table must contain some rows and columns.

**Comment by quoininc-huudatran** [comment]
As I said, I understand what you are saying, BUT, i do not have any table in my doc definition, so I do not know where it comes from.

**Comment by liborm85** [comment]
I don't see document definition. Attach it.

**Comment by quoininc-huudatran** [comment]
[doc-definition-no-working.txt](https://github.com/bpampuch/pdfmake/files/3426675/doc-definition-no-working.txt)

You might have to change the fonts to a standard one. I'm not sure how to attach the fonts.

**Comment by quoininc-huudatran** [comment]
Finally got time to get back to this... If I remove that `toc` because it is empty, the document generates fine, so this really tells me that the issue is the empty `toc`.

**Comment by liborm85** [comment]
You can try new version (0.1.58).

**Comment by quoininc-huudatran** [comment]
Do you think the TOC should be displayed if it's empty? The code doesn't break anymore.

Thanks,

**Comment by liborm85** [comment]
New property `hideEmpty` implemented by commit https://github.com/bpampuch/pdfmake/commit/6634ed480ace1fe5bc1cf5d9228dc10741a42fba.

**Comment by liborm85** [comment]
Feature released in version 0.3.3.
