### ISSUE TITLE
Firebase functions deploy error

### ISSUE THREAD

**Issue by jeisonng** [bpampuch/pdfmake#1784]
I need help for deploy in firebase functions, the deploy return erro:

My import from pdfmake:

`const Printer = require("pdfmake/src/printer");`

erro:

`Function failed on loading user code. Error message: Code in file index.js can't be loaded.  
Did you list all required modules in the package.json dependencies?                          
Detailed stack trace: Error: Cannot find module 'pdfmake/src/printer'                        
    at Function.Module._resolveFilename (module.js:548:15)                                   
    at Function.Module._load (module.js:475:25)                                              
    at Module.require (module.js:597:17)                                                     
    at require (internal/module.js:11:18)                                                    
    at Object.<anonymous> (/srv/domain/user.js:7:17)                                         
    at Module._compile (module.js:653:30)                                                    
    at Object.Module._extensions..js (module.js:664:10)                                      
    at Module.load (module.js:566:32)                                                        
    at tryModuleLoad (module.js:506:12)                                                      
    at Function.Module._load (module.js:498:3) `

**Comment by liborm85** [comment]
Probably pdfmake not available on path `pdfmake/src/printer`.
