### ISSUE TITLE
Cannot run on FreeBSD Server

### ISSUE THREAD

**Issue by labadze** [bpampuch/pdfmake#1795]
If I run server side version on  OS X it works fine but on VPS FreeBSD I getting 
`Error: Cannot find module 'pdfMake'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at app.get (/usr/local/www/back-end/app.js:925:21)
    at Layer.handle [as handle_request] (/usr/local/www/back-end/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/www/back-end/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/www/back-end/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/www/back-end/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/www/back-end/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/www/back-end/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/www/back-end/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/www/back-end/app.js:100:5
    at Layer.handle_error (/usr/local/www/back-end/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/local/www/back-end/node_modules/express/lib/router/index.js:315:13)`

**Comment by liborm85** [comment]
pdfmake may not be installed or not accessible.

**Comment by labadze** [comment]
Thanks for responding, I have found another way to make my task complete.
