### ISSUE TITLE
Minified version not working - Tested with Chrome & Firefox & Angularjs 1.2.4

### ISSUE THREAD

**Issue by almoraleslopez** [bpampuch/pdfmake#18]
Hi.

I'm trying to get pdfmake working with Angularjs, but when I try to use the minified version it is not working.

With createPdf(dd).open() is not working (No error message)
With createPdf(dd).print() I have this error message:
Error: No unicode cmap for font
at a.registerTTF (pdfmake.min.js:3:10521)
    at new a (pdfmake.min.js:3:8885)
    at d.b.exports.font (pdfmake.min.js:5:506)
    at n.provideFont (pdfmake.min.js:7:5740)
    at pdfmake.min.js:7:13190
    at Array.forEach (native)
    at i (pdfmake.min.js:7:13048)
    at c.buildInlines (pdfmake.min.js:7:13653)
    at c.measureLeaf (pdfmake.min.js:6:13905)
    at build/pdfmake.min.js:6:13070 

With no-minified version is working fine.

**Comment by jacksnose** [comment]
Has anyone continued to experience this error, even when using the non-minified version?
