### ISSUE TITLE
PDF with SVG won't generate with SVG with upgrade from 0.60.0 -> 0.1.61

### ISSUE THREAD

**Issue by Bene-Graham** [bpampuch/pdfmake#1834]
I am currently getting an error when rendering the pdf that has an svg with in it. It was working fine on version 0.1.60.

```
TypeError: Cannot read property 'normal' of undefined
    at options.fontCallback (/Web/node_modules/pdfmake/src/printer.js:635:34)
    at recursive (/Web/node_modules/svg-to-pdfkit/source.js:2238:32)
    at /Web/node_modules/svg-to-pdfkit/source.js:2376:9
    at new SvgElemText (/Web/node_modules/svg-to-pdfkit/source.js:2380:9)
    at createSVGElement (/Web/node_modules/svg-to-pdfkit/source.js:642:29)
    at SvgElemSvg.SvgElem.getChildren (/Web/node_modules/svg-to-pdfkit/source.js:1288:27)
    at SvgElemSvg.SvgElemHasChildren.drawChildren (/Web/node_modules/svg-to-pdfkit/source.js:1382:29)
    at SvgElemSvg.SvgElemContainer.drawContent (/Web/node_modules/svg-to-pdfkit/source.js:1403:14)
    at SvgElemSvg.drawInDocument (/Web/node_modules/svg-to-pdfkit/source.js:1518:14)
    at SVGtoPDF (/Web/node_modules/svg-to-pdfkit/source.js:2473:14)
    at renderSVG (/Web/node_modules/pdfmake/src/printer.js:638:15)
    at renderPages (/Web/node_modules/pdfmake/src/printer.js:406:6)
    at PdfPrinter.createPdfKitDocument (/Web/node_modules/pdfmake/src/printer.js:171:2)
    at /Web/services/reports/pdfBuilderBase.js:87:37
    at new Promise (<anonymous>)
    at SpecPDFBuilder.saveToBuffer (/Web/services/reports/pdfBuilderBase.js:81:16)
    at SpecPDFBuilder.build (/Web/services/reports/employeeBenefits/quote/newSpecReport.js:783:21)
    at NewQuoteSpecReport.render (/Web/services/reports/employeeBenefits/quote/newSpecReport.js:33:35)
    at async /Web/routes/report.js:350:36
```

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   version="1.1"
   id="Capa_1"
   x="0px"
   y="0px"
   viewBox="0 0 297.5 297.5"
   style="enable-background:new 0 0 297.5 297.5;"
   xml:space="preserve"
   sodipodi:docname="arrow.svg"
   inkscape:version="1.0beta1 (32d4812, 2019-09-19)"><metadata
   id="metadata147">
  <rdf:RDF>
    <cc:Work
   rdf:about="">
      <dc:format>image/svg+xml</dc:format>

      <dc:type
   rdf:resource="http://purl.org/dc/dcmitype/StillImage" />

    </cc:Work>

  </rdf:RDF>

</metadata>

<defs
   id="defs145">
  <rect
   x="245.39474"
   y="114.47368"
   width="261.18422"
   height="57.236842"
   id="rect980" />

</defs>

<sodipodi:namedview
   pagecolor="#ffffff"
   bordercolor="#666666"
   inkscape:document-rotation="0"
   borderopacity="1"
   objecttolerance="10"
   gridtolerance="10"
   guidetolerance="10"
   inkscape:pageopacity="0"
   inkscape:pageshadow="2"
   inkscape:window-width="1440"
   inkscape:window-height="829"
   id="namedview143"
   showgrid="false"
   inkscape:zoom="0.35"
   inkscape:cx="400"
   inkscape:cy="560"
   inkscape:window-x="0"
   inkscape:window-y="203"
   inkscape:window-maximized="0"
   inkscape:current-layer="Capa_1" />


<polygon
   points="297.5,148.25 148,33.25 148,100.25 0,100.25 0,199.25 148,199.25 148,264.25 "
   id="polygon110"
   style="fill:#ffff00;stroke:#000000;stroke-opacity:1;stroke-width:3;stroke-miterlimit:4;stroke-dasharray:none" />


<g
   id="g112">
</g>


<g
   id="g114">
</g>


<g
   id="g116">
</g>


<g
   id="g118">
</g>


<g
   id="g120">
</g>


<g
   id="g122">
</g>


<g
   id="g124">
</g>


<g
   id="g126">
</g>


<g
   id="g128">
</g>


<g
   id="g130">
</g>


<g
   id="g132">
</g>


<g
   id="g134">
</g>


<g
   id="g136">
</g>


<g
   id="g138">
</g>


<g
   id="g140">
</g>


<text
   xml:space="preserve"
   id="text978"
   style="font-style:normal;font-weight:normal;font-size:48px;line-height:1.25;font-family:sans-serif;shape-inside:url(#rect980);fill:#000000;fill-opacity:1;stroke:none"
   transform="translate(-226.72934,1.9736842)"><tspan
     x="245.39453"
     y="158.26646"
     sodipodi:role="line"><tspan
       style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:45.3333px;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold'">Due </tspan><tspan
       style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold'">Date:</tspan></tspan></text>

</svg>
```

Any ideas?

**Comment by liborm85** [comment]
New version 0.1.62 improves finding font from svg definition. Maybe it solve this issue.

**Comment by Bene-Graham** [comment]
Updating to v0.1.62 has solved the issue.

Thanks!
