### ISSUE TITLE
adding a toc gives error; without it the pdf generates fine

### ISSUE THREAD

**Issue by evereveron** [bpampuch/pdfmake#1904]
I get this error when I add a toc: 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageNumber' of undefined
    at preparePageNodeRefLine (/Users/mm33280/Documents/src/metadata-tool/node_modules/pdfmake/src/printer.js:422:46)
    at renderLine (/Users/mm33280/Documents/src/metadata-tool/node_modules/pdfmake/src/printer.js:440:3)
    at renderPages (/Users/mm33280/Documents/src/metadata-tool/node_modules/pdfmake/src/printer.js:388:6)
```

my doc definition looks like this:

```
let docDefinition: docDefinition = {
            content: [
                { toc: {
                    title: { text: 'Table of Contents', style: 'header'},
                    numberStyle: { bold: true }
                }},
                { text: 'Title Text' , style: 'header', tocItem: true},
                { text: 'Section 1',
                  style: 'sectionTitle',
                  tocItem: true,
                  pageBreak: 'before' },
            ],
            styles: {
                header: {
                    fontSize: 20
                },
                sectionTitle: {
                    fontSize: 18
                },
            }
            defaultStyle: {
                fontSize: 8
            }
        };
```
Then some more content is dynamically added to the content array, including some content that would have `tocItem: true`. 

I am not sure what the error means though. Without the toc, the exact same pdf generates correctly, so why would a page be undefined with the toc added?

**Comment by liborm85** [comment]
Attach full example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by liborm85** [comment]
No reaction.

**Comment by jdinard** [comment]
I'm having a similar issue

**Comment by liborm85** [comment]
The question is still being asked.

**Comment by AUtech-dev** [comment]
I also had this issue.

One problem I found: I added a text with `tocItem: true` but with an empty text. This leads to the problem.

~~~js
{
			text: '', // note the empty text!
			style: 'subheader',
			tocItem: true,
			pageBreak: 'before'
		},
~~~

Complete example for http://pdfmake.org/playground.html

~~~js
var dd = {
	content: [
		{
			text: 'This is a TOC example. Text elements marked with tocItem: true will be located in the toc. See below.',
			pageBreak: 'after'
		},
		{
			toc: {
				title: { text: 'INDEX', style: 'header' },
				//textMargin: [0, 0, 0, 0],
				//textStyle: {italics: true},
				numberStyle: { bold: true }
			}
		},
		{
			text: 'This is a header, using header style',
			style: 'header',
			tocItem: true,
			tocStyle: { italics: true },
			tocMargin: [0, 10, 0, 0],
			tocNumberStyle: { italics: true, decoration: 'underline' },
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam.\n\n',
		{
			text: '', // note the empty text!
			style: 'subheader',
			tocItem: true,
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true
		},
		subheader: {
			fontSize: 15,
			bold: true
		},
		quote: {
			italics: true
		},
		small: {
			fontSize: 8
		}
	}
};
~~~


Error message:

~~~
printer.js:419 Uncaught (in promise) TypeError: Cannot read property 'pageNumber' of undefined
    at i (printer.js:419)
    at printer.js:437
    at printer.js:385
    at i.createPdfKitDocument (printer.js:160)
    at pdfMake.js:81
i @ printer.js:419
(anonymous) @ printer.js:437
(anonymous) @ printer.js:385
i.createPdfKitDocument @ printer.js:160
(anonymous) @ pdfMake.js:81
Promise.then (async)
u._createDoc @ pdfMake.js:80
u.getBuffer @ pdfMake.js:252
u.getDataUrl @ pdfMake.js:229
generate @ playground.html:124
(anonymous) @ playground.html:114
setTimeout (async)
(anonymous) @ playground.html:112
r._signal @ ace.js:1
onChange @ ace.js:1
r._signal @ ace.js:1
applyDelta @ ace.js:1
insertMergedLines @ ace.js:1
insert @ ace.js:1
insert @ ace.js:1
insert @ ace.js:1
exec @ ace.js:1
(anonymous) @ ace.js:1
r._emit.r._dispatchEvent @ ace.js:1
exec @ ace.js:1
$callKeyboardHandlers @ ace.js:1
onTextInput @ ace.js:1
onTextInput @ ace.js:1
A @ ace.js:1
O @ ace.js:1
~~~

![grafik](https://user-images.githubusercontent.com/72972651/96248681-38670800-0fac-11eb-9fe0-67ba011ccf92.png)

**Comment by AUtech-dev** [comment]
@liborm85 Can you reproduce the issue with my example? https://github.com/bpampuch/pdfmake/issues/1904#issuecomment-709967824

I think this issue should be reopened as more information is available. (But I can not do it myself?)
