### ISSUE TITLE
"TypeError: URLBrowserResolver is not a constructor" error in nodejs since V0.1.66

### ISSUE THREAD

**Issue by Steve-Mcl** [bpampuch/pdfmake#2037]
Hi, prior to v0.1.66, calls to `getBuffer()` and `getBase64()` worked perfectly well in NODE (v12) but since the addition of URLBrowserResolver.js in V0.1.66 the following code fails...

```
const pdfDocGenerator = pdfMake.createPdf(docDefinition, options);
pdfDocGenerator.getBuffer((buffer) => {
                    msg.payload = new Buffer(buffer);
                    this.send(msg);
                });
```

First run, this error occurs...
```
ReferenceError: window is not defined
    at Object.<anonymous> (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\src\browser-extensions\URLBrowserResolver.js:4:1)
    at __webpack_require__ (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\webpack\bootstrap:19:1)
    at Document._createDoc (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\src\browser-extensions\pdfMake.js:50:27)
    at Document.getBuffer (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\src\browser-extensions\pdfMake.js:252:1)
    at pdfmake._inputCallback (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\pdfmake\pdfmake.js:27:33)
    at pdfmake.Node._emitInput (c:\programdata\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:200:18)
    at Immediate._onImmediate (c:\programdata\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:179:33)
    at processImmediate (internal/timers.js:456:21) {stack: 'ReferenceError: window is not defined
    at … processImmediate (internal/timers.js:456:21)', message: 'window is not defined'}
```

subsequent runs, this error occurs...
```
TypeError: URLBrowserResolver is not a constructor
    at Document._createDoc (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\src\browser-extensions\pdfMake.js:51:1)
    at Document.getBuffer (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\node_modules\pdfmake\build\webpack:\src\browser-extensions\pdfMake.js:252:1)
    at pdfmake._inputCallback (c:\Users\Stephen\.node-red\node_modules\node-red-contrib-pdfmake\pdfmake\pdfmake.js:27:33)
    at pdfmake.Node._emitInput (c:\programdata\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:200:18)
    at Immediate._onImmediate (c:\programdata\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:179:33)
    at processImmediate (internal/timers.js:456:21) {stack: 'TypeError: URLBrowserResolver is not a constr… processImmediate (internal/timers.js:456:21)', message: 'URLBrowserResolver is not a constructor'}
```

![image](https://user-images.githubusercontent.com/44235289/88898603-dc120900-d244-11ea-8f71-9fd7dcd9c4f7.png)

**Comment by Steve-Mcl** [comment]
As a (very) dirty hack, to get things working in node (when calling getBuffer() etc) I have temporarily hacked a few lines of code into the built pdfmake,js as followings...

```
  var isNode=new Function("try {return this===global;}catch(e){return false;}");
  if(isNode()){
    var doc = printer.createPdfKitDocument(this.docDefinition, options);
    cb(doc);
    return doc;
  }
```

like this....
![image](https://user-images.githubusercontent.com/44235289/88902594-5729ee00-d24a-11ea-826e-3144d07760d8.png)

**Comment by liborm85** [comment]
`window` fixed by commit https://github.com/bpampuch/pdfmake/commit/74ccc8864f2fc0df5dbd61e150d3d1be4fdd93ee.

**Comment by Steve-Mcl** [comment]
I have tested this on a local copy. Seems to do the trick.

**Comment by liborm85** [comment]
New version released.
