### ISSUE TITLE
Font Error - calling pdfmake via JSInterop

### ISSUE THREAD

**Issue by robertjiles** [bpampuch/pdfmake#2538]
Hi,

I am trying to us an alternative font but can't get past this issue.
Front end application is written in Blazor - we are live and make very good use of pdfmake for generating printed consumer documents. Have made use of a package PDFMakeNET to construct the document definition in c# and convert to JSON for creation. This doesn't implement custom fonts at the moment - this is the part I am developing. 

Have followed the online font details (ideally I want to implement url fonts - but am going step by step at the moment).
Created a new vsf_fonts.js file to contain the font definitons (small screenshot below). I'm happy this is not the issue as I can swap one of the roboto font definitions with mine and the correct font is used.

![image](https://user-images.githubusercontent.com/123257184/215499535-d67a0000-9b30-42d0-8674-797a9fe1648e.png)

Below is cut down document definition (i've just removed some of the styles that are not used for ease of reading).
I have added my new font definition to the fonts section (I have also tried with Arial and Robot fonts defined - same result).

{
"fonts":{"lighthouse":{"normal":"lighthouse.ttf","bold":"lighthouse.ttf","italics":"lighthouse.ttf","bolditalics":"lighthouse.ttf"}}
,"header":[]
,"footer":[]
,"content":[{"text":"Some Text In Default Font","style":["bill_for"]}]
,"defaultStyle":{"font":"lighthouse"}
,"styles":{
"bill_for":{"fontSize":16,"bold":true,"color":"#37277c","margin":[25,25,0,0]}
,"hidden":{"color":"white"}
,"hidden_0":{"color":"white","height":0}
,"small":{"fontSize":8}
}
,"pageSize":"A4","pageMargins":[10,120,10,35]}

When I run this via JSInterop - get the following error:

fontProvider.js:52 Uncaught (in promise) Error: Font 'lighthouse' in style 'bold' is not defined in the font section of the document definition.
    at FontProvider.provideFont (fontProvider.js:52:9)
    at textTools.js:326:27
    at Array.forEach (<anonymous>)
    at measure (textTools.js:298:13)
    at TextTools.buildInlines (textTools.js:32:17)
    at DocMeasure.measureLeaf (docMeasure.js:235:28)
    at docMeasure.js:59:30
    at StyleContextStack.auto (styleContextStack.js:143:15)
    at DocMeasure.measureNode (docMeasure.js:44:25)
    at DocMeasure.measureVerticalContainer (docMeasure.js:289:19)
Uncaught (in promise) Error: Font 'lighthouse' in style 'bold' is not defined in the font section of the document definition.

If I don't set the font in the defualt style - it works fine (with Roboto font).
If I set the font explicitly on the content text line - I get the same issue.

Could you confirm / advise if I have added the font details correctly:
"fonts":{"lighthouse":{"normal":"lighthouse.ttf","bold":"lighthouse.ttf","italics":"lighthouse.ttf","bolditalics":"lighthouse.ttf"}}

I have tried adding as an array of fonts (included Roboto and arial) but no joy. 
Have also tried calling it font (rather tham fonts) - as the error details font section, but this is just the text returned from fontProvider.js.
Tested in Chrome browser using:
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
as the source. Have also tried a few other versions but same result.

Any help / advice you could provide would be most appreciated.

Thankyou.

**Comment by robertjiles** [comment]
Found the issue - fonts are passed in as a separate paramter, not part of the document definition.
