### ISSUE TITLE
Error when using with vite production build

### ISSUE THREAD

**Issue by mpiannucci** [bpampuch/pdfmake#2573]
Version: 0.3.0-beta.5

When using in a react app with vite, I am importing the library like this:

```typescript
import pdfFonts from 'pdfmake/build/vfs_fonts';
import pdfMake from "pdfmake/build/pdfmake";
```

Then to build the pdf: 

```typescript
pdfMake.addVirtualFileSystem(pdfFonts);
pdfMake.createPdf(pdfDefinition).download(title);
```

This results in an opaque error: 

```
caught (in promise) TypeError: Assignment to constant variable.
    at Ke.add (ScreenshotUtils-3859fc43.js:2587:107585)
    at ht.planPreprocessing (ScreenshotUtils-3859fc43.js:2587:109034)
    at ht.plan (ScreenshotUtils-3859fc43.js:2587:108866)
    at Ke.setup (ScreenshotUtils-3859fc43.js:2587:207739)
    at Ke.layout (ScreenshotUtils-3859fc43.js:2587:209613)
    at Ke.layout (ScreenshotUtils-3859fc43.js:2587:248250)
    at Pe.value (ScreenshotUtils-3859fc43.js:2546:5134)
    at Pe.value (ScreenshotUtils-3859fc43.js:2546:5450)
    at Pe.value (ScreenshotUtils-3859fc43.js:2546:5729)
    at Pe.value (S
```

This code works fine when running with vite locally. 

Im not expecting a fix, just posting in case someone else has run into this, and so I can post when I figure out why it is happening. 

Right now, there is an output line while building: 

```
Illegal reassignment of import "commonjsHelpers" in "node_modules/pdfmake/build/pdfmake.js".
```
Which may be the culprit

**Comment by mpiannucci** [comment]
Upgrading to vite 4.2.1 from 4.0.1 fixed this issue for me
