### ISSUE TITLE
Fonts not working properly when added through vfs

### ISSUE THREAD

**Issue by MathanM** [bpampuch/pdfmake#2585]
I added a font file through vfs, but getting the following error

`ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'xCoordinate')
TypeError: Cannot read properties of null (reading 'xCoordinate')
    at GPOSProcessor.getAnchor (pdfmake.js:61223:20)
    at GPOSProcessor.applyAnchor (pdfmake.js:61213:27)
    at GPOSProcessor.applyLookup (pdfmake.js:61127:16)
    at GPOSProcessor.applyLookups (pdfmake.js:58918:26)
    at GPOSProcessor.applyFeatures (pdfmake.js:58899:10)
    at GPOSProcessor.applyFeatures (pdfmake.js:61242:43)
    at ShapingPlan.process (pdfmake.js:58494:19)
    at OTLayoutEngine.position (pdfmake.js:61336:17)
    at LayoutEngine.position (pdfmake.js:61450:32)
    at LayoutEngine.layout (pdfmake.js:61428:10)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1282:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:25441:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25441:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Object.onInvokeTask (core.mjs:25749:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)`
    
    I have attached the font file and font [download link](https://fonts.google.com/noto/specimen/Noto+Sans+Telugu?query=telugu)
    
    Try translating this text to repro this issue "ప్రత్యేక లక్షణాలు"
    
[font.zip](https://github.com/bpampuch/pdfmake/files/11547021/font.zip)

**Comment by phanindravarma412** [comment]
I had  the same issue. Did you find any solution ?

**Comment by n5r** [comment]
FWIW, I was experiencing this issue and for a quick hackaround simply edited `node_modules/fontkit/dist/main.cjs getAnchor` around line 9991 and added this as the first line in the `getAnchor` method:

```
if (!anchor) return {x:0, y:0};
```

Seemed to work for quick and dirty fix.

**Comment by liborm85** [comment]
Bug is in [fontkit](https://github.com/foliojs/fontkit).

**Comment by liborm85** [comment]
pdfmake use fontkit library for rendering fonts, create issue [here](https://github.com/foliojs/fontkit).

**Comment by roo12312** [comment]
im also facing the same issue! what is the solution?
