### ISSUE TITLE
TypeError: 'get' on proxy: property '_layoutEngine' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<LayoutEngine2>' but got '#<LayoutEngine2>')

### ISSUE THREAD

**Issue by SleepyAsh0191** [bpampuch/pdfmake#2782]
```
Uncaught (in promise) TypeError: 'get' on proxy: property '_layoutEngine' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<LayoutEngine2>' but got '#<LayoutEngine2>')
    at Proxy.layout (index.js:11603:1)
    at Proxy.layoutRun (embedded.js:32:27)
    at Proxy.layoutCached (embedded.js:56:22)
    at Proxy.layout (embedded.js:81:26)
    at Proxy.widthOfString (embedded.js:118:24)
    at widthOfString (textTools.js:370:1)
    at TextTools.widthOfString (textTools.js:118:1)
    at LayoutBuilder.buildNextLine (layoutBuilder.js:804:1)
    at LayoutBuilder.processLeaf (layoutBuilder.js:714:1)
    at layoutBuilder.js:403:1
```

![image](https://github.com/user-attachments/assets/9f836759-a2a0-45e4-a228-125541f56658)
when i'm using Simsun.ttf for unicode text

**Comment by atpznn** [comment]
i have same issue 
anyone has solution? 
I'm guessing several reasons. Using slash ,
Number of characters used
But I still can't find it.

**Comment by liborm85** [comment]
Not related with pdfmake. Bug is in [fontkit](https://github.com/foliojs/fontkit).
