### ISSUE TITLE
Build Project issue with pdfmake "0.2.7" version.

### ISSUE THREAD

**Issue by ShamimMahmud25** [bpampuch/pdfmake#2802]
Build error occurred
TypeError: Cannot read properties of undefined (reading 'vfs')
    at 65638 (E:\FrontEnd\ffbd-admin\.next\server\chunks\6887.js:1174:57)
    at __webpack_require__ (E:\FrontEnd\ffbd-admin\.next\server\webpack-runtime.js:25:42)
    at 33024 (E:\FrontEnd\ffbd-admin\.next\server\pages\shopping-centre\sales-report.js:4888:17)
    at __webpack_require__ (E:\FrontEnd\ffbd-admin\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (E:\FrontEnd\ffbd-admin\.next\server\pages\shopping-centre\sales-report.js:8206:39)
    at E:\FrontEnd\ffbd-admin\.next\server\pages\shopping-centre\sales-report.js:8207:202
    at __webpack_require__.X (E:\FrontEnd\ffbd-admin\.next\server\webpack-runtime.js:190:21)
    at E:\FrontEnd\ffbd-admin\.next\server\pages\shopping-centre\sales-report.js:8207:47
    at Object.<anonymous> (E:\FrontEnd\ffbd-admin\.next\server\pages\shopping-centre\sales-report.js:8210:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  type: 'TypeError'
}
error Command failed with exit code 1.

I was using "pdfmake": "^0.2.7", it worked fine previously, but for yesterday it cause the build failure.

**Comment by liborm85** [comment]
Version 0.2.7 is too old, update to latest version [0.2.15](https://github.com/bpampuch/pdfmake/releases/tag/0.2.15).

**Comment by ShamimMahmud25** [comment]
I have updated it to 0.2.15, still issue exists.

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.

**Comment by kthomas182** [comment]
I got it working by doing:

import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.addVirtualFileSystem(pdfFonts);

**Comment by mtrefzer** [comment]
I'm using typescript and and having the same issue.
It seems like a problem with the latest `@types/pdfmake@0.2.9`.

Within `vfs_fonts.d.ts` there is the namespace, that doesn't match with the actual build of `pdfmake@0.2.15`:
```
export namespace pdfMake {
    let vfs: { [file: string]: string };
}
```

**Comment by liborm85** [comment]
Format VFS was changed i 0.2.15 for better compatibility with frameworks (see [changelog](https://github.com/bpampuch/pdfmake/releases/tag/0.2.15)).
`@types/pdfmake` is not part of pdfmake, contact the author.

**Comment by ShamimMahmud25** [comment]
I solved this by the following code. Althougth there is type error remaining , I am ignoring type error in my project.
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts;

Previously I used 
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;
