### ISSUE TITLE
Cannot insert image with base64 string, 

### ISSUE THREAD

**Issue by nabil-rady** [bpampuch/pdfmake#2825]
I am running pdfmake in Next 14 on WSL 2, I can't seem to be able to add any images to the pdf using base64 string

Provided below are my usage and a traceback. 

```js
let docDefinition = {
      content: [
        {
          image:
            'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAAA5CAYAAABArXsrAAAIXElEQVR4Xu1caWwVVRQ+TfxhQmJbSJQgIAURQwNIWUKBCrIGRYFAlVrZF1EIpWIFEZBdFqFQAREQiYKoLVI2K7ukKIbNSAIREcomQZOCBUn8YVL73eS8zJvO65s3M53bsWf+dXLvzLnf+eacc797XuPKKy6SSxAIIAJxQt4Aek1MVggIeYUIgUVAyBtY14nhQl7hQGAREPIG1nViuJBXOBBYBIS8gXWdGC7kFQ4EFgEhb2BdJ4YLeYUDgUVAC3kvXSqhS5dLFGh9evcILHhiuF4EfCfvR+s/ocJde6l1q2QqPnaczp3/hQ7uK6QO7VP0IiFvDxwCvpIXEfeFQRlU/F0R1a2bqMBq2KQl3bv3N5Vc/Dl0L3AoisFaEPCVvIuX5tLM2QtoyOAB9MXWTWrB095+l5bnrqbPP9tIL6YP0gKCvDSYCPhKXkTeSVk5lJ31eqjWZfKuyXufXh0/KpgoitVaEPCVvFYr7JzWR9W9UjZo8X+gX6qVvPsPHKZnn08nibqB5pA247WR9/btO5TUvA0tfW+ulAva3B/sF2shL4jbf8BLtCp3sZLI8PedO39Rs2ZJ2tFEDc5X2d27tG5NrnabapsB4MOSZStp67Z8unXrD6pf/xHKzEinaTlTwhQpLeRFncvEhWOgQqS0baP9wOLkqTOUlT2drl2/oUDr3esZKtpTUNu4o3W9IG5a937Khl07tqmAxhIr7p07+2PIPt/JOzRzNJWV3VWHFHzt2bsvZKhT5PABIHovqShD3F4TJmbTxo8/pQXzZtL0t7LdPs7V/H79h4SpM64eFoDJrD59szs/LJjx/mhq9qSQj30lL+u8Vhj++0+pK2g53XtB3uTWnejCrxfp+LED2k/+kKXmzJ6uPSu5ck4Mk+PrNab79++TFR8eeLCeKiFuXDmvnugreWNYQ8xDvSIv0tbDDR6nOnXqUFnptZjt8HpCbSIvR9cWTzQPKw8YUyY2BxUhr4ltX+XvoJeHja0x9W5tIi9n5o4d2tEPxfsrxQFgceLk6ZC0Wom8iDz5BYV0ueQKJSYmqJoP97gXwfxEfC2HDh9Vt3v26KbSGwrs9Rs3q3s4Cvaj6caryGusdxMTEhQOuMaPHVlJDQEuWCdqbWCFMcAJzUdG/NxE4+ogL9sHu5omNakxUiXXu9HIy3VvGHlBxPShI6lzake1Sfi6cDcVFx+nG7/fVPfMO2+8DJ1hUya/ppyFvgU8GBLHrBk5dORoMRV9e5DOnDha7TKYV+Tlehe1VdcunWj0yFdo0+Ytah3G7jfeAfd/rq/6aLOnzlAcbdWqpdqQjhqRSeMmZFHG0MGu5DYvyYus8kbOO9S4UUMaMSxDfXBz5y+h+PiHLCOd8aNDVNy1u8jxd2hUlyI9xDF5OV0am2bwEg7VY8cMD3MCxq/M+zBs0egQg8SEE7NePbtTi+T2yk7zztExAlVM9IK8XO/iNeZTP2wWjLUYSJ67fFFoI4VoNnHym6ENBVSVgu07KVIUsYuBV+Rl+4z+5XuwJdqGGdicOv2TXbMrjbPTt+2IvHzahV3enzd/CysR2AlmZ4KoOwq2hJUEcDADAc00tWtv5XBjC6Tj1VdMZDnM6hnIALjSuqZavoJLoKrezxsGK8IZ18Y9ycZMxMBzSoPEdeDgkahH3yzIR7ILWQwZ4LHGjSyHtEt5Kmo3Hq/LuFPHw6y6/Nz4x+1cR+RlgpqjLozhaHrh3Kmw1A9AjF9TVY53uyie74a8eEY0GY3BM+u7xoiMjxs1Li7jiSBnqFizjFvy2qlZ2TYr3RpBxo89iR0OOCIvSxDm6Iq6Dqnf/MVaGWKOPHaM9XKMF2VDJAJyScVZxcpuY2T2cl1uywbOgLDJHIBisdOPsoFxjiSVcSDlABFXIT2UI71bLc6qToq0YKeRJxYAqxrrBXkjEZAViEigVmfWcUteLg3sBKCq8PVjw8bBMlKQYP9waRu3b/+hcrQlWony5noXf6/9YLmqieGwkpKrIZnFyvEwZtmKPFe7bbvk9oq8VvWucSOKhnmWyNIHD1SlQ6Ssg/tupUK35I2Wiu3i69c4DoLmvRcT2+ifuNLS2+U4UTI7DQ5qndJFqQdIN9jw4G8czRlTEU47QGII++ZneEEou6B58S6UT8ktnwxTUKyiKm/GuHGH5TVjvcv4nT3zvavf5rklL/sqkuoBOzOHj6sxDUhWPQzgAGc/I8ZK5zWznTt7oO/yObORHOaTEP41RMNHG4SO9WDE6HGTyK3z/CQvMgv0XP5VBxzfq+9AwrqMiglIjmvDulWUkBCvtHHgxL/DY0J0e7qL68Yet+SFnZF+rcI+giZfk36CZSxXobJcvXZd+cXc+63Iy2RF/yoEbLQErli2UO2qoV2i1oOQvWfnlyqKcFTBWAjyaWmpNGbUsJCjMRaXHWHaLjmjjfMi8nKfMdaPteHnSThkWDR/dlj0xMe7eu0GNQbr37xprfoRKQBG5MY9HF5EUzeirYmJ57Yxh9eF9cA+XFgjJLiF82ZV+wGSnXWax6BMyN9eWOn00jgu7IQNkQaENUpg/A9CrERmfLnNmiaFFs87UpQYfssvIBQuL1oYGYf27dpGTPlWuNiZF6sjUaLMmzPDEzzZPthg59AgVlv9Hv+/aczxGzh5n34EhLz6fSAWOERAyOsQOJmmHwEhr34fiAUOERDyOgROpulHQMir3wdigUMEhLwOgZNp+hEQ8ur3gVjgEAEhr0PgZJp+BIS8+n0gFjhEQMjrEDiZph8BIa9+H4gFDhEQ8joETqbpR0DIq98HYoFDBIS8DoGTafoREPLq94FY4BABIa9D4GSafgSEvPp9IBY4REDI6xA4maYfASGvfh+IBQ4R+A+6O4qhAailYgAAAABJRU5ErkJggg==',
        },
      ],
    };
```
 

```
web:dev: Error: invalid distance too far back
web:dev:     at Zlib._handle.onerror (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:25280:37)
web:dev:     at Zlib._error (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24889:26)
web:dev:     at Zlib._checkError (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24867:34)
web:dev:     at Zlib._after (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24873:31)
web:dev:     at /home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24755:31
web:dev:     at Item.run (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42931:30)
web:dev:     at Timeout.drainQueue [as _onTimeout] (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42903:58)
web:dev:     at listOnTimeout (node:internal/timers:569:17)
web:dev:     at process.processTimers (node:internal/timers:512:7) {
web:dev:   errno: -3,
web:dev:   code: 'Z_DATA_ERROR'
web:dev: }
web:dev:  ⨯ uncaughtException: Error: invalid distance too far back
web:dev:     at Zlib._handle.onerror (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:25280:37)
web:dev:     at Zlib._error (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24889:26)
web:dev:     at Zlib._checkError (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24867:34)
web:dev:     at Zlib._after (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24873:31)
web:dev:     at /home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24755:31
web:dev:     at Item.run (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42931:30)
web:dev:     at Timeout.drainQueue [as _onTimeout] (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42903:58)
web:dev:     at listOnTimeout (node:internal/timers:569:17)
web:dev:     at process.processTimers (node:internal/timers:512:7) {
web:dev:   errno: -3,
web:dev:   code: 'Z_DATA_ERROR'
web:dev: }
web:dev:  ⨯ uncaughtException: Error: invalid distance too far back
web:dev:     at Zlib._handle.onerror (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:25280:37)
web:dev:     at Zlib._error (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24889:26)
web:dev:     at Zlib._checkError (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24867:34)
web:dev:     at Zlib._after (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24873:31)
web:dev:     at /home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:24755:31
web:dev:     at Item.run (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42931:30)
web:dev:     at Timeout.drainQueue [as _onTimeout] (/home/nabil/ki-schulgenie-ai-boilerplate/apps/web/dist/server/chunks/d22e3_pdfmake_build_pdfmake_4341fd.js:42903:58)
web:dev:     at listOnTimeout (node:internal/timers:569:17)
web:dev:     at process.processTimers (node:internal/timers:512:7) {
web:dev:   errno: -3,
web:dev:   code: 'Z_DATA_ERROR'
web:dev: }
```

**Comment by liborm85** [comment]
Tested on playground and all is correct:
![image](https://github.com/user-attachments/assets/b82c0bc9-ddef-4cba-8adc-589a64dcbbe8)

The problem will be in something other than pdfmake.
