### ISSUE TITLE
dev-playground does not run since module.uri is undefined

### ISSUE THREAD

**Issue by exoego** [bpampuch/pdfmake#576]
I am trying to run dev-playground locally, but can not, since _serve.js_ does not run.

According to stacktrace, _module.uri_ is _undefined_ on line 12 of _server.js_.

> var rootDir = path.resolve(path.dirname(module.uri));

I could not find any resolution to set _module.uri_, since I am new to node.js...
Any help?
# Logs

$ cd dev-playground
$ npm install
(successfully installed)
$ cd ..
$ nodemon ./dev-playground/server.js
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: _._
[nodemon] starting `node ./dev-playground/server.js`
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/Users/yt/IdeaProjects/dragons-pdf/dev-playground/server.js:12:33)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by liborm85** [comment]
Fixed by https://github.com/bpampuch/pdfmake/pull/759
