### ISSUE TITLE
Style dictionaries don't work with new versions of Node.js

### ISSUE THREAD

**Issue by RPGillespie6** [bpampuch/pdfmake#747]
I'm not sure why, but it seems as though Style dictionaries do not work if your node version is too new. The error thrown if you try to use style dictionaries is as follows:

```
/home/user/hns-swagger/node_modules/pdfkit/js/font/tables/name.js:59
      this.postscriptName = strings[6][0].raw.replace(/[\x00-\x19\x80-\xff]/g, "");
                                      ^

TypeError: Cannot read property '0' of undefined
    at NameTable.parse (/home/user/hns-swagger/node_modules/pdfkit/js/font/tables/name.js:59:39)
    at NameTable.Table (/home/user/hns-swagger/node_modules/pdfkit/js/font/table.js:13:14)
    at new NameTable (/home/user/hns-swagger/node_modules/pdfkit/js/font/tables/name.js:19:46)
    at TTFFont.parse (/home/user/hns-swagger/node_modules/pdfkit/js/font/ttf.js:96:19)
    at new TTFFont (/home/user/hns-swagger/node_modules/pdfkit/js/font/ttf.js:89:14)
    at Function.TTFFont.open (/home/user/hns-swagger/node_modules/pdfkit/js/font/ttf.js:37:14)
    at new PDFFont (/home/user/hns-swagger/node_modules/pdfkit/js/font.js:32:31)
    at PDFDocument.module.exports.font (/home/user/hns-swagger/node_modules/pdfkit/js/mixins/fonts.js:39:20)
    at FontWrapper.getFont (/home/user/hns-swagger/node_modules/pdfmake/src/fontWrapper.js:36:41)
    at FontWrapper.widthOfString (/home/user/hns-swagger/node_modules/pdfmake/src/fontWrapper.js:47:18)
    at /home/user/hns-swagger/node_modules/pdfmake/src/textTools.js:220:21
    at Array.forEach (native)
    at measure (/home/user/hns-swagger/node_modules/pdfmake/src/textTools.js:205:13)
    at TextTools.buildInlines (/home/user/hns-swagger/node_modules/pdfmake/src/textTools.js:28:17)
    at DocMeasure.measureLeaf (/home/user/hns-swagger/node_modules/pdfmake/src/docMeasure.js:178:28)
    at /home/user/hns-swagger/node_modules/pdfmake/src/docMeasure.js:58:30

```

I'm using node `v.4.2.6`. It last worked when I had  `v0.10.32`

**Comment by liborm85** [comment]
Try lastest pdfmake version.

**Comment by liborm85** [comment]
In actual node version 6.9.1, me it works.
