### ISSUE TITLE
Cannot find module 'linebreak'

### ISSUE THREAD

**Issue by oscar-espada** [bpampuch/pdfmake#832]
Hi,

When I run the node application, I get this error:

```
Error: Cannot find module 'linebreak'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/esmasshopping/api/node_modules/pdfmake/src/textTools.js:4:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/esmasshopping/api/node_modules/pdfmake/src/docMeasure.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Could be the "linebreak" dependence in package.json?
Thanks.

**Comment by miltador** [comment]
Hi @oscar-espada,
Thanks for noticing! `linebreak` was accidentally added to `devDependencies` list.
